package com.szakdologzat.repiceapp.domain;

import static com.szakdologzat.repiceapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class RecipeBookAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookAllPropertiesEquals(RecipeBook expected, RecipeBook actual) {
        assertRecipeBookAutoGeneratedPropertiesEquals(expected, actual);
        assertRecipeBookAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookAllUpdatablePropertiesEquals(RecipeBook expected, RecipeBook actual) {
        assertRecipeBookUpdatableFieldsEquals(expected, actual);
        assertRecipeBookUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookAutoGeneratedPropertiesEquals(RecipeBook expected, RecipeBook actual) {
        assertThat(expected)
            .as("Verify RecipeBook auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookUpdatableFieldsEquals(RecipeBook expected, RecipeBook actual) {
        assertThat(expected)
            .as("Verify RecipeBook relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getTheme()).as("check theme").isEqualTo(actual.getTheme()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getTags()).as("check tags").isEqualTo(actual.getTags()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookUpdatableRelationshipsEquals(RecipeBook expected, RecipeBook actual) {
        // empty method
    }
}
