package com.szakdologzat.repiceapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecipeBookRelationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookRelationAllPropertiesEquals(RecipeBookRelation expected, RecipeBookRelation actual) {
        assertRecipeBookRelationAutoGeneratedPropertiesEquals(expected, actual);
        assertRecipeBookRelationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookRelationAllUpdatablePropertiesEquals(RecipeBookRelation expected, RecipeBookRelation actual) {
        assertRecipeBookRelationUpdatableFieldsEquals(expected, actual);
        assertRecipeBookRelationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookRelationAutoGeneratedPropertiesEquals(RecipeBookRelation expected, RecipeBookRelation actual) {
        assertThat(expected)
            .as("Verify RecipeBookRelation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookRelationUpdatableFieldsEquals(RecipeBookRelation expected, RecipeBookRelation actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecipeBookRelationUpdatableRelationshipsEquals(RecipeBookRelation expected, RecipeBookRelation actual) {
        assertThat(expected)
            .as("Verify RecipeBookRelation relationships")
            .satisfies(e -> assertThat(e.getRecipe()).as("check recipe").isEqualTo(actual.getRecipe()))
            .satisfies(e -> assertThat(e.getRecipeBook()).as("check recipeBook").isEqualTo(actual.getRecipeBook()));
    }
}
